### ISSUE TITLE
Add support for user-defined configuration

### ISSUE THREAD

**Issue by jcantosz** [boxboat/dockhand#46]
As a user I would like to be able to define my own configuration to use with my own library functions and pipelines. An example of what this might look like is:
```yaml
common:
  userConfigMap:
    toolConfig:
      configLocation: "/path/to/config"
      additionalOptions: "--option value"
```
