### ISSUE TITLE
Behavior not documented on configuration set in jenkins.yaml

### ISSUE THREAD

**Issue by jcantosz** [boxboat/dockhand#48]
I would expect that defining a configuration in a `jenkins.yaml` would merge with, instead of replace configuration defined in `config.yaml`. The documentation does not state which should happen. Experimentation points to replacement instead of merging. Is this the desired behavior?

## example
`config.yaml`:
```yaml
repo:
  common:
    eventRegistryKeys:
      - event: commit/develop
         registryKey: develop
      - event: commit/master
        registryKey: master
      - eventRegex: commit/release/(.*)
        registryKey: release
```

`jenkins.yaml`:
```yaml
common:
  eventRegistryKeys:
     - event: commit/develop
       registryKey: develop-alternative
build:
  eventRegistryKeys:
     - event: commit/master
       registryKey: master-alternative
```

I would expect a common pipeline to have the config available to it:
```yaml
eventRegistryKeys:
  - event: commit/develop
    registryKey: develop-alternative
  - event: commit/master
    registryKey: master
  - eventRegex: commit/release/(.*)
     registryKey: release
```

Instead it can only accessy:
```yaml
eventRegistryKeys:
  - event: commit/develop
    registryKey: develop-alternative
```

I would expect my build pipeline to have the config available to it:
```yaml
eventRegistryKeys:
  - event: commit/develop
    registryKey: develop-alternative
  - event: commit/master
    registryKey: master-alternative
  - eventRegex: commit/release/(.*)
     registryKey: release
```

Instead it can only access:
```yaml
eventRegistryKeys:
  - event: commit/master
    registryKey: master-alternative
```

**Comment by caleblloyd** [comment]
This is a tough situation. Appending to a list, or merging map keys would create a situation where you would not be able to delete list items or map keys. Replacing involves more copying, but it does allow for setting the desired state.

To support merging we would really need to introduce support for multiple files that could be applied with something like http://jsonpatch.com/

**Comment by jcantosz** [comment]
I can see how a deletion would be desirable. It sounds like the current behavior is intended, I update the  docs to make that clear.

I do not think more files to be applied is the answer, or that the level of granularity that JSONPatch provides is necessary. If we want to make an enhancement to support this, I think we could take inspiration from JSONPatch but have it apply to the whole jenkins YAML file (ie, either merge or replace) via a base level key in the `jenkins.yaml` like:
```yaml
# Merge with config.yaml
merge: true
common: ...
```
which defaults to `false` and the current behavior.
```yaml
# DEFAULT Replace values in config.yaml with the ones below
merge: false
common: ...
```
