### ISSUE TITLE
gitRepo.getBranch() for Pull Requests

### ISSUE THREAD

**Issue by caleblloyd** [boxboat/dockhand#62]
Presently, `gitRepo.getBranch()` returns the name of the PR, such as `PR-1` for pull requests

Example setup:

![image](https://user-images.githubusercontent.com/2414837/84691214-7267c500-af4c-11ea-9459-dd39b5655af9.png)

1. I create a feature branch - `feature/my-feature`
2. I have logic to deploy to a feature preview environment based on `commit/feature/my-feature`
3. I open a PR to merge to `master` -  `PR-1` is built
4. I receive a code review and push a fix to the feature branch
5. With the above settings, the feature branch is no longer built, but a PR build is built
6. `gitRepo.getBranch()` returns `PR-2` as the branch name, which does not match `commit/feature/my-feature`
7. My feature preview environment is not deployed :frowning: 

My inclination is to have `gitRepo.getBranch()` return the `CHANGE_BRANCH` environment variable, if set:

![image](https://user-images.githubusercontent.com/2414837/84691637-2b2e0400-af4d-11ea-87d4-bef02e5657e8.png)

About the only downside that I can see is that if pull requests from forks in an untrusted environment (such as the public) are allowed, this would be a security issue:

![image](https://user-images.githubusercontent.com/2414837/84692030-ddfe6200-af4d-11ea-90f9-00b444b7c397.png)

I am not aware of any projects using this library that allow this, so it may not be an issue.

**Comment by jcantosz** [comment]
I have a similar use-case that I was planning to implement. Was planning to do this:
```
repo:
  common:
    eventRegistryKeys:
      - eventRegex: commit/PR-(.*)
        registryKey: pr
      ...
  deploy:
    deploymentMap:
      pr:
        environmentKey: dev
        eventRegex: commit/PR-(.*)
        trigger: true
     ...
```
I think this has the benefit of not caring about what the branch is named (only that a PR was opened), but it is obviously less readable as a user/in the deployment environment
